### ISSUE TITLE
pangolin.config.js not loaded on Windows

### ISSUE THREAD

**Issue by DuvanNR** [pangolinjs/core#109] opened 2022-04-22 20:27 UTC
Currently I have tried to do some tests with pangolin.js but when using Windows OS the pangolin.config.js file doesn't work. On Linux OS it works perfectly.

The curious thing is that when compiling the project on windows, pangolin.js shows no errors.

Could you please help me understand this situation?

Greetings!

**Comment by DuvanNR** [comment] 2022-04-25 07:00
> Thank you for reporting this issue. I never really tested on Windows, so I didn’t catch this earlier.
> 
> I will investigate in the the next days. I don’t have to much spare time in the coming week, though, so I ask for your patience 🙂

Thanks for your reply!!

**Comment by mvsde** [comment] 2022-05-04 06:13
The issue is resolved in [v6.1.2](https://github.com/pangolinjs/core/releases/tag/v6.1.2).

**Closed by mvsde** 2022-05-04 06:13 UTC
Labels: bug

**Comment by DuvanNR** [comment] 2022-05-05 01:00
> The issue is resolved in [v6.1.2](https://github.com/pangolinjs/core/releases/tag/v6.1.2).

Thank you so much!!!!
